import { Colors } from './src/Theme';

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  important: true,
  theme: {
    extend: {
        borderWidth: {
          2: '2px',
          7: '7px',
        },
        colors: {
            main: Colors.main,
            main2: Colors.main2,
            main3: Colors.main3, 
            main4: Colors.main4,
            main5: Colors.main5,
            yellow: Colors.yellow,
            orange: Colors.orange,
            light: Colors.light,  
            lightMain: Colors.lightMain,
            hoverMain: Colors.hoverMain,
            second: Colors.second,
            input: Colors.input,
            gray: Colors.gray,
            gray2: Colors.gray2,
            gray_l: Colors.gray_l,
            gray_input: Colors.gray_input,
            body: Colors.body,
            olive: Colors.olive,
            lightRed: Colors.lightRed,
            grayDC: Colors.grayDC,
            bgBL: Colors.bgBL,
            red: Colors.red,
            hoverRed: Colors.hoverRed,
            green: Colors.green,
            hoverGreen: Colors.hoverGreen,
            bg: Colors.bg,
            hoverGray: Colors.hoverGray,
            Black60: Colors.Black60,
            Gray1: Colors.Gray1,
            Black3: Colors.Black3,
            input_fill: Colors.input_fill,
            gold: Colors.gold,
            gold2: Colors.gold2,
            hoverGold: Colors.hoverGold,
            lightGray: Colors.lightGray,
            danger: Colors.danger,
            success: Colors.success,
            lightSuccess: Colors.lightSuccess,
            failed: Colors.failed,
            lightFailed: Colors.lightFailed,
            black2: Colors.black2, 
            black3: Colors.black3,
            black4: Colors.black4,
            black5: Colors.black5,
            black6: Colors.black6,
            gray3: Colors.gray3,
            gray4: Colors.gray4,
            gray5: Colors.gray5,
            gray6: Colors.gray6,
            gray7: Colors.gray7,
            gray8: Colors.gray8,
        },
    },
  },
  plugins: [],
  // Disable Tailwind's preflight to prevent conflicts with MUI
  corePlugins: {
    preflight: false,
  },
} 